### ISSUE TITLE
Jommla 3.X support

### ISSUE THREAD

**Issue by unitoneict** [icos-urenio/Improve-my-city#116]
I just want to ask if you plan to update the code to work with 3.X?

I Already review the current repo but it is not up-to-date?
https://github.com/icos-urenio/improve-my-city-Joomla-3

As you all know, Jommla stop the support for 2.X at the end of 2014, this may effect the usability of the project

Regards,

**Comment by davinci440** [comment]
I am looking to help for the development of Improve my City version that is compatible with joomla 3.0 
I am planning to create a crowdfunding project so we can help and pay developer finish the Improve my city version for joomla 3.0 So the question is, how much money we need to fund and finish the project_

**Comment by unitoneict** [comment]
I think that IMC must be redeveloped to be more generic and easy to migrate even between Joomla version, or other CMS like WP ... etc.

**Comment by TGoodrich** [comment]
I to am wondering the status for Joomla 3 compatibility. I have been following the status for the past year and there have been hints of IMC for Joomla 3 but thats about it. I have a Joomla 3 town website and this is the one extension I would really like to implement.

**Comment by itsam** [comment]
Hi there,
IMC3 will be released end of this month
It is written and implemented from scratch and contains plugins, modules
and the core component for maximum freedom.
Many new features added (e.g. frontend editing, multiple issue status, etc)
I also attach a screenshot from the frontend

[image: Inline image 1]
...and consider that most of the changes took place at backend :)

So stay in touch!

Best
Ioannis Tsampoulatidis

**Comment by unitoneict** [comment]
Can you please upload the image?

**Comment by unitoneict** [comment]
@itsam , any updates?

**Comment by itsam** [comment]
Visit https://github.com/itsam/imc for beta version

**Comment by unitoneict** [comment]
Is there any document highlighted the change log and the new enhancements?

**Comment by itsam** [comment]
You can check this temporary site: http://mklab.iti.gr/joomla3
