### ISSUE TITLE
Strict Standards errors

### ISSUE THREAD

**Issue by asehir** [icos-urenio/Improve-my-city#118]
I have following errors and I tried to update but lost it all. Please let me know what to do. Thanks.

http://asehir.net/demo/

Strict Standards: Only variables should be assigned by reference in /home/asehir/public_html/demo/components/com_improvemycity/controller.php on line 23

Strict Standards: Declaration of ImprovemycityModelIssues::populateState() should be compatible with JModelList::populateState($ordering = NULL, $direction = NULL) in/home/asehir/public_html/demo/components/com_improvemycity/models/issues.php on line 24

Strict Standards: Only variables should be assigned by reference in /home/asehir/public_html/demo/components/com_improvemycity/models/discussions.php on line 41

Strict Standards: Only variables should be assigned by reference in /home/asehir/public_html/demo/components/com_improvemycity/models/discussions.php on line 41

Strict Standards: Only variables should be assigned by reference in /home/asehir/public_html/demo/components/com_improvemycity/models/discussions.php on line 41

Strict Standards: Only variables should be assigned by reference in /home/asehir/public_html/demo/components/com_improvemycity/models/discussions.php on line 41

Strict Standards: Only variables should be assigned by reference in /home/asehir/public_html/demo/components/com_improvemycity/models/discussions.php on line 41

Strict Standards: Only variables should be assigned by reference in /home/asehir/public_html/demo/components/com_improvemycity/models/discussions.php on line 41

Strict Standards: Only variables should be assigned by reference in /home/asehir/public_html/demo/components/com_improvemycity/models/discussions.php on line 41

**Comment by itsam** [comment]
is due to newest PHP default settings. Nevertheless I suggest you to check https://github.com/itsam/imc

**Comment by asehir** [comment]
Hi. Thanks for your reply. I actually checked and installed that one as you can see http://asehir.net/demo/

Now I have some problems with module positions :) I was using a yootheme template but filter and map module did not work well so I am trying to use your template but it's also not very useful.

Do you advise any other template ?

Thanks.

**Comment by itsam** [comment]
Any bootstrap-bases should be fine. Alternatively, I am planning to release hopefully next week a bootstrap free IMC. Currently, If you are technically savvy, you can just include latest bootstrap library but that will cause a major overhead on top of Yootheme (just a quick and dirty solution)

**Comment by asehir** [comment]
Ok I will wait for new bootstrap them next week. Can I download that one on the link.

http://mklab.iti.gr/joomla3/en/demo

**Comment by itsam** [comment]
This one is an open source template called purity iii. You can download from https://www.joomlart.com/joomla/templates/purity-iii

**Comment by asehir** [comment]
Thanks a lot.
