### ISSUE TITLE
Seems Incompatible with Joomla! 3.4.5

### ISSUE THREAD

**Issue by ootws** [icos-urenio/Improve-my-city#121]
Site version: Joomla! 3.4.5
Improve My City component version: 2.6.0

Not sure whey, but these are errors I`m getting now with this component.

Administrator:
Fatal error: Call to undefined method JController::getInstance() in /usr/home/example/public_html/administrator/components/com_improvemycity/improvemycity.php on line 25

Site:
Fatal error: Call to undefined method JController::getInstance() in /usr/home/example/public_html/components/com_improvemycity/improvemycity.php on line 19

I thought I'd attempt legacy with JControllerLegacy, but no go. Just a white page so I can only assume more needs correcting to make this component compatible.

**Comment by itsam** [comment]
Please check this repo: https://github.com/itsam/imc
