### ISSUE TITLE
API KEY Problem

### ISSUE THREAD

**Issue by superdiogene** [icos-urenio/Improve-my-city#122]
Hi I downloaded the IMC-master for joomla 3> but I always receive an error message that I enclose, that does not make me view the maps. I tried to create the apikey but I see that they are of different types and I'm losing. Could you help me please?
Thank you
![errore_mapp](https://cloud.githubusercontent.com/assets/3618862/12079757/40ac15ce-b245-11e5-865d-c695bd697487.png)
![google_map](https://cloud.githubusercontent.com/assets/3618862/12079758/4aa601f2-b245-11e5-9cad-8851db79edc2.png)

**Comment by itsam** [comment]
Please make sure you are using the correct repository: https://github.com/itsam/imc
If you have problems open an issue at https://github.com/itsam/imc/issues
